import { z } from "zod";

export const sectionSchema = z.object({
  id: z.number(),
  header: z.string(),
  type: z.string(),
  status: z.string(),
  target: z.string(),
  limit: z.string(),
  reviewer: z.string(),
  ssl: z.boolean().optional(),
  url: z.string().optional(),
  host: z.string().optional(),
  path: z.string().optional(),
  query: z.string().optional(),
  format: z.string().optional(),
  statusGroup: z.string().optional(),
  client: z.string().optional(),
  method: z.string().optional(),
  code: z.number().optional(),
  date: z.string().optional(),
  time: z.string().optional(),
  duration: z.number().optional(),
  timeComplete: z.number().optional(),
  requestTotalTime: z.number().optional(),
  responseTotalTime: z.number().optional(),
  latency: z.number().optional(),
  requestBodySize: z.number().optional(),
  responseBodySize: z.number().optional(),
  serverIpAddress: z.string().optional(),
  edited: z.boolean().optional(),
  comment: z.string().optional(),
});
